language: objective-c
osx_image: xcode11.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=ASCollectionView.xcworkspace
  - SCHEME=ASCollectionView
  - SDK=iphonesimulator13.2
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=13.2.2,name=iPhone 11 Pro"
    - DESTINATION="OS=12.1,name=iPhone X"
    - DESTINATION="OS=11.4,name=iPhone 8"
    - DESTINATION="OS=10.3.1,name=iPhone 6"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/ASCollectionView-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

after_success: slather
